"""add next_job_id

Revision ID: abbdadda1485
Revises: 0002_job_runtime_spec
Create Date: 2026-06-07 16:03:31.813209

"""
from alembic import op
import sqlalchemy as sa
import app


revision = 'abbdadda1485'
down_revision = '0002_job_runtime_spec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('next_job_id', app.db.types.GUID(length=36), nullable=True))
    op.drop_index(op.f('ix_jobs_enabled'), table_name='jobs')
    op.create_foreign_key(None, 'jobs', 'jobs', ['next_job_id'], ['id'], ondelete='SET NULL')
    op.add_column('tasks', sa.Column('processed_for_chaining', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'processed_for_chaining')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_index(op.f('ix_jobs_enabled'), 'jobs', ['enabled'], unique=False)
    op.drop_column('jobs', 'next_job_id')
    # ### end Alembic commands ###
