"""replace next_job_id with job_dependencies

Revision ID: 447fbff8c51d
Revises: abbdadda1485
Create Date: 2026-06-08 18:51:38.555478

"""
from alembic import op
import sqlalchemy as sa
import app


revision = '447fbff8c51d'
down_revision = 'abbdadda1485'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_dependencies',
    sa.Column('upstream_job_id', app.db.types.GUID(length=36), nullable=False),
    sa.Column('downstream_job_id', app.db.types.GUID(length=36), nullable=False),
    sa.ForeignKeyConstraint(['downstream_job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upstream_job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('upstream_job_id', 'downstream_job_id')
    )
    op.drop_constraint(op.f('jobs_next_job_id_fkey'), 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'next_job_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('next_job_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('jobs_next_job_id_fkey'), 'jobs', 'jobs', ['next_job_id'], ['id'], ondelete='SET NULL')
    op.drop_table('job_dependencies')
    # ### end Alembic commands ###
